version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

    
  celery_worker:
    build: .
    #command: ["./wait-for-it.sh", "redis:6379", "--", "celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info"]
    container_name: celery-worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis



  app:
    build: .
    container_name: fastapi-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    #command: ["./wait-for-it.sh", "redis:6379", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis