version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
  celery:
    build: .
    command: celery -A app.tasks.celery_worker worker --loglevel=info
